name: Publish Docker Image
on:
  push:
    branches:
      - master
  release:
    types: [published]
jobs:
  push_to_registry:
    if: github.repository == 'scilifelabdatacentre/dsw-appendix'
    name: Publish Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Log in to Github Container Repository
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/scilifelabdatacentre/dsw-appendix
            scilifelabdatacentre/dsw-appendix
      - name: Build and Publish
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
